version: '3'
services:
  golang_database:
    container_name: golang_database
    image: postgres:13.7-alpine3.15
    restart: always
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - /postgresql_golang/data:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - golang_project_network

  mailhog:
    image: mailhog/mailhog
    restart: always
    logging:
      driver: 'none'  # disable saving logs
    ports:
      - "1025:1025" # smtp server
      - "8025:8025" # web ui


#volumes:
#  static_volume:
#  redis_data:
#  elasticsearch-data:
#    driver: local

networks:
  golang_project_network:
      driver: bridge